name: "hubble-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - /^release-.*$/
    paths:
      - hugegraph-hubble/**
      - hugegraph-dist/**
      - hugegraph-loader/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-hubble/**
      - hugegraph-dist/**
      - hugegraph-loader/**
      - hugegraph-client/**
      - .github/workflows/**
      - pom.xml

env:
  TRAVIS_DIR: hugegraph-hubble/hubble-dist/assembly/travis
  # TODO: replace it with the (latest - n) commit id (n >= 15)
  # FIXME: hugegraph commit date: 2025-10-30
  COMMIT_ID: 8c1ee71 # 5b3d295

jobs:
  hubble-ci:
    runs-on: ubuntu-latest
    env:
      USE_STAGE: 'true' # Whether to include the stage repository.
      STATIC_DIR: hugegraph-hubble/hubble-dist/assembly/static
    strategy:
      matrix:
        JAVA_VERSION: ['11']
        python-version: ["3.11"]

    steps:
      - name: Fetch Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          cache-dependency-path: 'hugegraph-hubble/hubble-fe/yarn.lock'

      # we also should cache python & yarn & downloads to avoid useless work
      - name: use staged maven repo settings
        if: ${{ env.USE_STAGE == 'true' }}
        run: |
          mkdir -p $HOME/.m2
          if [ -f $HOME/.m2/settings.xml ]; then cp $HOME/.m2/settings.xml /tmp/settings.xml; fi
          mv -vf .github/configs/settings.xml $HOME/.m2/settings.xml

      - name: Compile
        run: |
          mvn install -pl hugegraph-client,hugegraph-loader -am -Dmaven.javadoc.skip=true -DskipTests -ntp || exit 1
          cd hugegraph-hubble && ls * || true
          mvn -e compile -Dmaven.javadoc.skip=true -ntp || exit 1

      - name: Prepare env and service
        run: |
          python -m pip install -r ${TRAVIS_DIR}/requirements.txt || exit 1
          cd hugegraph-hubble
          mvn package -Dmaven.test.skip=true -ntp || exit 1
          cd apache-hugegraph-hubble-incubating*
          cd bin
          ./start-hubble.sh -d || exit 1
          sleep 5
          ./stop-hubble.sh || true
          cd ../../../
          pwd
          $TRAVIS_DIR/install-hugegraph.sh $COMMIT_ID || exit 1

      - name: Unit test
        run: mvn test -P unit-test -pl hugegraph-hubble/hubble-be -ntp || exit 1

      - name: API test
        env:
          CI: false
        run: |
          cd hugegraph-hubble && ls || true
          $TRAVIS_DIR/run-api-test.sh || exit 1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: hugegraph-hubble/hubble-be/target/site/jacoco/*.xml
