name: "loader-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - /^release-.*$/
    paths:
      - hugegraph-loader/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-loader/**
      - hugegraph-dist/**
      - hugegraph-client/**
      - .github/workflows/**
      - pom.xml

jobs:
  loader-ci:
    runs-on: ubuntu-latest
    env:
      USE_STAGE: 'true' # Whether to include the stage repository.
      TRAVIS_DIR: hugegraph-loader/assembly/travis
      STATIC_DIR: hugegraph-loader/assembly/static
      # TODO: replace it with the (latest - n) commit id (n >= 15)
      # hugegraph commit date: 2025-10-30
      COMMIT_ID: 5b3d295
      DB_USER: root
      DB_PASS: root
      DB_DATABASE: load_test
    strategy:
      matrix:
        JAVA_VERSION: ['11', '17']

    steps:
      - name: Fetch Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install JDK ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: use staged maven repo settings
        if: ${{ env.USE_STAGE == 'true' }}
        run: |
          cp $HOME/.m2/settings.xml /tmp/settings.xml
          mv -vf .github/configs/settings.xml $HOME/.m2/settings.xml

      - name: Compile
        run: |
          mvn install -pl hugegraph-client,hugegraph-loader -am -Dmaven.javadoc.skip=true -DskipTests -ntp

      - name: Prepare env and service
        run: |
          $TRAVIS_DIR/install-hadoop.sh
          $TRAVIS_DIR/install-mysql.sh ${{ env.DB_DATABASE }} ${{ env.DB_PASS }}
          $TRAVIS_DIR/install-hugegraph-from-source.sh $COMMIT_ID

      - name: Run test
        run: |
          cd hugegraph-loader
          mvn test -P unit -ntp || exit 1
          mvn test -P file -ntp || exit 1
          mvn test -P hdfs -ntp || exit 1
          mvn test -P jdbc -ntp || exit 1
          mvn test -P kafka -ntp || exit 1
        continue-on-error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: always() && matrix.JAVA_VERSION == '11'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: hugegraph-loader/target/jacoco.xml
          fail_ci_if_error: false
